# [1] Este archivo sirve para levantar los servicios de Grafana y Prometheus usando Docker Compose.
# [2] Ejecutar este archivo con el comando: docker-compose up -d (estando en el directorio donde se encuentra el "docker-compose.yml")

# [3] Ejecutar "docker-compose restart prometheus" para reiniciar el servicio de Prometheus
# [4] Ejecutar "docker-compose restart grafana" para reiniciar el servicio de Grafana

version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3008:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
